apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: ramansawhney04/currency-exchange-devops:latest 
        imagePullPolicy: IfNotPresent
        name: currency-conversion
        # env:
        #   - name: CURRENCY_EXCHANGE_SERVICE_HOST
        #     value: http://currency-exchange
        
        #     valueFrom: 
        #       configMapKeyRef:
        #         key: CURRENCY_EXCHANGE_SERVICE_HOST
        #         name: currency-conversion-config-map
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: currency-conversion-ingress
   labels:
     app: currency-conversion
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /  
 spec:
   rules:
   - host: java-project.tech-learning.live
     http:
       paths:
       - path: 
         backend:
           serviceName: currency-conversion
           servicePort: 8000